AppBundle\Entity\AzMemberFav:
    type: entity
    table: az_member_fav
    id:
        fid:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 收藏时间
            id: true
            generator:
                strategy: IDENTITY
    fields:
        mid:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 'member id'
                default: '0'
        tid:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 'topic id'
                default: '0'
    lifecycleCallbacks: {  }
