AppBundle\Entity\AzTags:
    type: entity
    table: az_tags
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: Id
            generator:
                strategy: IDENTITY
    fields:
        tagname:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        parentid:
            type: integer
            nullable: true
            options:
                unsigned: false
    lifecycleCallbacks: {  }
