AppBundle\Entity\AzTopicExpert:
    type: entity
    table: az_topic_expert
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        tid:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
        mid:
            type: integer
            nullable: true
            options:
                unsigned: false
        addtime:
            type: integer
            nullable: true
            options:
                unsigned: false
    lifecycleCallbacks: {  }
