AppBundle\Entity\DedeAddonspec:
    type: entity
    table: dede_addonspec
    indexes:
        typeid:
            columns:
                - typeid
    id:
        aid:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        typeid:
            type: smallint
            nullable: false
            options:
                unsigned: true
                default: '0'
        note:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        templet:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
                default: ''
        userip:
            type: string
            nullable: false
            length: 15
            options:
                fixed: true
                default: ''
        redirecturl:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                default: ''
    lifecycleCallbacks: {  }
