AppBundle\Entity\DedeMoneycardType:
    type: entity
    table: dede_moneycard_type
    id:
        tid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        num:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '500'
        money:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '50'
        pname:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: ''
    lifecycleCallbacks: {  }
