AppBundle\Entity\DedeCoMediaurls:
    type: entity
    table: dede_co_mediaurls
    indexes:
        hash:
            columns:
                - hash
    id:
        tofile:
            type: string
            nullable: false
            length: 60
            options:
                fixed: true
                default: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nid:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
        hash:
            type: string
            nullable: false
            length: 32
            options:
                fixed: true
                default: ''
    lifecycleCallbacks: {  }
