AppBundle\Entity\DedeRatings:
    type: entity
    table: dede_ratings
    id:
        id:
            type: string
            nullable: false
            length: 11
            options:
                fixed: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        totalVotes:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: total_votes
        totalValue:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: total_value
        usedIps:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: used_ips
    lifecycleCallbacks: {  }
