AppBundle\Entity\DedeLog:
    type: entity
    table: dede_log
    id:
        lid:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        adminid:
            type: smallint
            nullable: false
            options:
                unsigned: true
                default: '0'
        filename:
            type: string
            nullable: false
            length: 60
            options:
                fixed: true
                default: ''
        method:
            type: string
            nullable: false
            length: 10
            options:
                fixed: true
                default: ''
        query:
            type: string
            nullable: false
            length: 200
            options:
                fixed: true
                default: ''
        cip:
            type: string
            nullable: false
            length: 15
            options:
                fixed: true
                default: ''
        dtime:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
    lifecycleCallbacks: {  }
