AppBundle\Entity\DedeMemberStow:
    type: entity
    table: dede_member_stow
    indexes:
        uid:
            columns:
                - mid
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        mid:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
        aid:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
        title:
            type: string
            nullable: false
            length: 60
            options:
                fixed: true
                default: ''
        addtime:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
        type:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
    lifecycleCallbacks: {  }
