AppBundle\Entity\DedeMultiservConfig:
    type: entity
    table: dede_multiserv_config
    id:
        remoteuploads:
            type: smallint
            nullable: false
            options:
                unsigned: false
                default: '0'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        remoteupurl:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: remoteupUrl
        rminfo:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        servinfo:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
    lifecycleCallbacks: {  }
