AppBundle\Entity\DedeAdmin:
    type: entity
    table: dede_admin
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        usertype:
            type: float
            nullable: true
            precision: 10
            scale: 0
            options:
                default: '0'
        userid:
            type: string
            nullable: false
            length: 30
            options:
                fixed: true
                default: ''
        pwd:
            type: string
            nullable: false
            length: 32
            options:
                fixed: true
                default: ''
        uname:
            type: string
            nullable: false
            length: 20
            options:
                fixed: true
                default: ''
        tname:
            type: string
            nullable: false
            length: 30
            options:
                fixed: true
                default: ''
        email:
            type: string
            nullable: false
            length: 30
            options:
                fixed: true
                default: ''
        typeid:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        logintime:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
        loginip:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
                default: ''
    lifecycleCallbacks: {  }
