AppBundle\Entity\DedeAdmintype:
    type: entity
    table: dede_admintype
    id:
        rank:
            type: float
            nullable: false
            precision: 10
            scale: 0
            options:
                default: '1'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        typename:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
                default: ''
        system:
            type: smallint
            nullable: false
            options:
                unsigned: false
                default: '0'
        purviews:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
    lifecycleCallbacks: {  }
