AppBundle\Entity\DedeVerifies:
    type: entity
    table: dede_verifies
    id:
        nameid:
            type: string
            nullable: false
            length: 32
            options:
                fixed: true
                default: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        cthash:
            type: string
            nullable: false
            length: 32
            options:
                fixed: false
                default: ''
        method:
            type: boolean
            nullable: false
            options:
                default: '0'
        filename:
            type: string
            nullable: false
            length: 254
            options:
                fixed: false
                default: ''
    lifecycleCallbacks: {  }
