AppBundle\Entity\DedeScores:
    type: entity
    table: dede_scores
    indexes:
        integral:
            columns:
                - integral
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        titles:
            type: string
            nullable: false
            length: 15
            options:
                fixed: true
        icon:
            type: smallint
            nullable: true
            options:
                unsigned: true
                default: '0'
        integral:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
        isdefault:
            type: boolean
            nullable: false
            options:
                default: '0'
    lifecycleCallbacks: {  }
