AppBundle\Entity\DedeShopsUserinfo:
    type: entity
    table: dede_shops_userinfo
    indexes:
        oid:
            columns:
                - oid
        userid:
            columns:
                - userid
    id:
        oid:
            type: string
            nullable: false
            length: 80
            options:
                fixed: false
                default: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        userid:
            type: integer
            nullable: false
            options:
                unsigned: false
        consignee:
            type: string
            nullable: false
            length: 15
            options:
                fixed: true
                default: ''
        address:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                default: ''
        zip:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
        tel:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                default: ''
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                default: ''
        des:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                default: ''
    lifecycleCallbacks: {  }
