AppBundle\Entity\DedeCoHtmls:
    type: entity
    table: dede_co_htmls
    indexes:
        nid:
            columns:
                - nid
        typeid:
            columns:
                - typeid
                - title
                - url
                - dtime
                - isdown
                - isexport
    id:
        aid:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nid:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
        typeid:
            type: smallint
            nullable: false
            options:
                unsigned: true
                default: '0'
        title:
            type: string
            nullable: false
            length: 60
            options:
                fixed: false
                default: ''
        litpic:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
                default: ''
        url:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
                default: ''
        dtime:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
        isdown:
            type: boolean
            nullable: false
            options:
                default: '0'
        isexport:
            type: boolean
            nullable: false
            options:
                default: '0'
        result:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
    lifecycleCallbacks: {  }
