AppBundle\Entity\DedeArcrank:
    type: entity
    table: dede_arcrank
    id:
        id:
            type: smallint
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        rank:
            type: smallint
            nullable: false
            options:
                unsigned: false
                default: '0'
        membername:
            type: string
            nullable: false
            length: 20
            options:
                fixed: true
                default: ''
        adminrank:
            type: smallint
            nullable: false
            options:
                unsigned: false
                default: '0'
        money:
            type: smallint
            nullable: false
            options:
                unsigned: true
                default: '500'
        scores:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
        purviews:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
    lifecycleCallbacks: {  }
