AppBundle\Entity\DedeSearchCache:
    type: entity
    table: dede_search_cache
    id:
        hash:
            type: string
            nullable: false
            length: 32
            options:
                fixed: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        lasttime:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
        rsnum:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
        ids:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
    lifecycleCallbacks: {  }
