AppBundle\Entity\DedeArccache:
    type: entity
    table: dede_arccache
    id:
        md5hash:
            type: string
            nullable: false
            length: 32
            options:
                fixed: true
                default: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        uptime:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
        cachedata:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
    lifecycleCallbacks: {  }
