AppBundle\Entity\DedeTagindex:
    type: entity
    table: dede_tagindex
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        tag:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                default: ''
        typeid:
            type: smallint
            nullable: false
            options:
                unsigned: true
                default: '0'
        count:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
        total:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
        weekcc:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
        monthcc:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
        weekup:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
        monthup:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
        addtime:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
    lifecycleCallbacks: {  }
