AppBundle\Entity\DedeHomepageset:
    type: entity
    table: dede_homepageset
    id:
        templet:
            type: string
            nullable: false
            length: 50
            options:
                fixed: true
                default: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        position:
            type: string
            nullable: false
            length: 30
            options:
                fixed: true
                default: ''
        showmod:
            type: boolean
            nullable: false
            options:
                default: '1'
    lifecycleCallbacks: {  }
