AppBundle\Entity\DedeUploads:
    type: entity
    table: dede_uploads
    indexes:
        memberid:
            columns:
                - mid
        arcid:
            columns:
                - arcid
    id:
        aid:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        arcid:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
        title:
            type: string
            nullable: false
            length: 60
            options:
                fixed: true
                default: ''
        url:
            type: string
            nullable: false
            length: 80
            options:
                fixed: true
                default: ''
        mediatype:
            type: smallint
            nullable: false
            options:
                unsigned: false
                default: '1'
        width:
            type: string
            nullable: false
            length: 10
            options:
                fixed: true
                default: ''
        height:
            type: string
            nullable: false
            length: 10
            options:
                fixed: true
                default: ''
        playtime:
            type: string
            nullable: false
            length: 10
            options:
                fixed: true
                default: ''
        filesize:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
        uptime:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
        mid:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
    lifecycleCallbacks: {  }
