AppBundle\Entity\DedePurview:
    type: entity
    table: dede_purview
    indexes:
        pkey:
            columns:
                - pkey
    id:
        pkey:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        mid:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
        typeid:
            type: smallint
            nullable: true
            options:
                unsigned: false
                default: '0'
        rank:
            type: smallint
            nullable: true
            options:
                unsigned: false
        pvalue:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
    lifecycleCallbacks: {  }
