AppBundle\Entity\DedeAddoninfos:
    type: entity
    table: dede_addoninfos
    indexes:
        typeid:
            columns:
                - typeid
                - nativeplace
                - infotype
        channel:
            columns:
                - channel
                - arcrank
                - mid
                - click
                - title
                - litpic
                - senddate
                - flag
                - endtime
    id:
        aid:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        typeid:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
        channel:
            type: smallint
            nullable: false
            options:
                unsigned: false
                default: '0'
        arcrank:
            type: smallint
            nullable: false
            options:
                unsigned: false
                default: '0'
        mid:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
        click:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
        title:
            type: string
            nullable: false
            length: 60
            options:
                fixed: false
                default: ''
        litpic:
            type: string
            nullable: false
            length: 60
            options:
                fixed: false
                default: ''
        userip:
            type: string
            nullable: false
            length: 15
            options:
                fixed: false
                default: ' '
        senddate:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
        flag:
            type: simple_array
            nullable: true
            length: null
            options:
                fixed: false
        lastpost:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
        scores:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
        goodpost:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
        badpost:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
        nativeplace:
            type: smallint
            nullable: false
            options:
                unsigned: true
                default: '0'
        infotype:
            type: string
            nullable: false
            length: 20
            options:
                fixed: true
                default: '0'
        body:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        endtime:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
        tel:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: ''
        email:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: ''
        address:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
                default: ''
        linkman:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: ''
    lifecycleCallbacks: {  }
