AppBundle\Entity\DedeSgpage:
    type: entity
    table: dede_sgpage
    indexes:
        ismake:
            columns:
                - ismake
                - uptime
        likeid:
            columns:
                - likeid
    id:
        aid:
            type: smallint
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 60
            options:
                fixed: false
                default: ''
        ismake:
            type: smallint
            nullable: false
            options:
                unsigned: false
                default: '1'
        filename:
            type: string
            nullable: false
            length: 60
            options:
                fixed: false
                default: ''
        keywords:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
                default: ''
        template:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
                default: ''
        likeid:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
                default: ''
        description:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
                default: ''
        uptime:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
        body:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
    lifecycleCallbacks: {  }
