AppBundle\Entity\DedeCoUrls:
    type: entity
    table: dede_co_urls
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        hash:
            type: string
            nullable: false
            length: 32
            options:
                fixed: false
                default: ''
        nid:
            type: smallint
            nullable: false
            options:
                unsigned: true
                default: '0'
    lifecycleCallbacks: {  }
