AppBundle\Entity\DedePlus:
    type: entity
    table: dede_plus
    id:
        aid:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        plusname:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
                default: ''
        menustring:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
                default: ''
        mainurl:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: ''
        writer:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
                default: ''
        isshow:
            type: smallint
            nullable: false
            options:
                unsigned: false
                default: '1'
        filelist:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
    lifecycleCallbacks: {  }
