AppBundle\Entity\DedePwdTmp:
    type: entity
    table: dede_pwd_tmp
    id:
        mid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        membername:
            type: string
            nullable: false
            length: 16
            options:
                fixed: true
                default: ''
        pwd:
            type: string
            nullable: false
            length: 32
            options:
                fixed: true
                default: ''
        mailtime:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
    lifecycleCallbacks: {  }
